kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-application
  labels:
    app: web-application
    workshop: workshop
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
        workshop: workshop
    spec:
      containers:
        - name: web-application
          image: bashofmann/k8s-workshop-web-application:8.0.1
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: db-mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ROOT_PASSWORD
                  name: mysql-secret
          envFrom:
            - configMapRef:
                name: web-application-config
          volumeMounts:
            - mountPath: /etc/web-application
              name: web-application-secret
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 1
            initialDelaySeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: web-application-secret
          secret:
            secretName: web-application-secret
