# The kube-controller-manager and kube-scheduler are managed and monitored by MetaKube itself
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    replicas: 2
    podAntiAffinity: hard

prometheus:
  prometheusSpec:
    retention: 4h
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    replicas: 1
    podAntiAffinity: hard
  ingress:
    enabled: true
    annotations:
      # type of authentication
      nginx.ingress.kubernetes.io/auth-type: basic
      # name of the secret that contains the user/password definitions
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
    hosts:
      - prometheus.workshop.metakube.org
    tls:
      - hosts:
          - prometheus.workshop.metakube.org

defaultRules:
  rules:
    kubernetesResources: true

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tlsProxy:
    enabled: false

grafana:
  adminPassword: admin
  ingress:
    enabled: true
    annotations:
      # type of authentication
      nginx.ingress.kubernetes.io/auth-type: basic
      # name of the secret that contains the user/password definitions
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
    hosts:
      - grafana.workshop.metakube.org
    tls:
      - hosts:
          - grafana.workshop.metakube.org
  grafana.ini:
    users:
      auto_assign_org_role: Editor
    auth:
      disable_login_form: true
    auth.basic:
      enabled: false
    auth.anonymous:
      enabled: true
      org_role: Editor
    analytics:
      check_for_updates: false

kubelet:
  enabled: true
  namespace: kube-system

  serviceMonitor:
    https: true
