apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prom
  name: mysql-rules
  namespace: monitoring
spec:
  groups:
    - name: ./mysql.rules
      rules:
        - alert: MySQLReplicationNotRunning
          expr: mysql_slave_status_slave_io_running == 0 or mysql_slave_status_slave_sql_running
            == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            description: Slave replication (IO or SQL) has been down for more than 2 minutes.
            summary: Slave replication is not running
        - alert: MySQLReplicationLag
          expr: (mysql_slave_lag_seconds > 30) and on(instance) (predict_linear(mysql_slave_lag_seconds[5m],
            60 * 2) > 0)
          for: 1m
          labels:
            severity: critical
          annotations:
            description: The mysql slave replication has fallen behind and is not recovering
            summary: MySQL slave replication is lagging
        - alert: MySQLReplicationLag
          expr: (mysql_heartbeat_lag_seconds > 30) and on(instance) (predict_linear(mysql_heartbeat_lag_seconds[5m],
            60 * 2) > 0)
          for: 1m
          labels:
            severity: critical
          annotations:
            description: The mysql slave replication has fallen behind and is not recovering
            summary: MySQL slave replication is lagging
        - alert: MySQLInnoDBLogWaits
          expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
          labels:
            severity: warning
          annotations:
            description: The innodb logs are waiting for disk at a rate of {{$value}} /
              second
            summary: MySQL innodb log writes stalling
